### ISSUE TITLE
FUNCTION_INVOCATION_FAILED

### ISSUE THREAD

**Issue by ShreyasNandanwar** [hussaino03/QuestLog#92]
![Screenshot 2024-12-05 133927](https://github.com/user-attachments/assets/857f2046-ff91-4844-9abe-d1214bc961f5)

**Comment by hussaino03** [comment]
@ShreyasNandanwar Thank you for opening the issue. Should be fixed now :) The problem was multiple requests made to current_user at the same time causing db timeout issues. Fixed it to ensure we only make the necessary requests instead.

**Comment by ShreyasNandanwar** [comment]
That's great! I will close this issue on my end. Thanks.
